<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\common.props" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Euonia.Business" />
		<PackageReference Include="Euonia.Domain" />
        <PackageReference Include="IdentityModel" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
	</ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Starfish.Toolkit\Starfish.Toolkit.csproj" />
    </ItemGroup>

</Project>
