<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\common.props" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
        <NoWarn>CS2002</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Euonia.Bus" />
		<PackageReference Include="Euonia.Business" />
		<PackageReference Include="Euonia.Domain" />
		<PackageReference Include="Euonia.Repository " />
		<PackageReference Include="IdentityModel" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Starfish.Shared\Starfish.Shared.csproj" />
		<ProjectReference Include="..\Starfish.Toolkit\Starfish.Toolkit.csproj" />
		<ProjectReference Include="..\Starfish.Transit\Starfish.Transit.csproj" />
	</ItemGroup>

    <!--
    <ItemGroup>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>
    -->

    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Nerosoft.Starfish.Toolkit" />
        <Using Include="$(RootNamespace).Properties" />
        <Using Include="Microsoft.Extensions.DependencyInjection" />
        <Using Include="System.Diagnostics.CodeAnalysis" />
    </ItemGroup>

</Project>
