<Project Sdk="Microsoft.NET.Sdk.Web">

	<Import Project="..\common.props" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<Description>A lightweight powerful distributed configuration server for .NET application.</Description>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)'=='Debug' ">
		<DebugType>full</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>CS2002;IDE0290;IDE0301;IDE0300</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)'=='Release' ">
		<DebugType>pdbonly</DebugType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<NoWarn>1591;CS2002;IDE0290;IDE0301</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Starfish.Application\Starfish.Application.csproj" />
	</ItemGroup>

</Project>
