<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\common.props" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Euonia.Linq" />
		<PackageReference Include="Euonia.Repository.EfCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="MongoDB.EntityFrameworkCore" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Starfish.Domain\Starfish.Domain.csproj" />
	</ItemGroup>

</Project>
