<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\common.props" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Starfish.Domain\Starfish.Domain.csproj" />
		<ProjectReference Include="..\Starfish.Transit\Starfish.Transit.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Euonia.Application" />
		<PackageReference Include="Euonia.Mapping.Automapper" />
	</ItemGroup>

</Project>
