<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\common.props" />

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
        <NoWarn>CS2002</NoWarn>
	</PropertyGroup>
    
	<ItemGroup>
		<PackageReference Include="DotLiquid" />
		<PackageReference Include="Euonia.Application" />
        <PackageReference Include="Euonia.Bus.InMemory" />
        <PackageReference Include="Euonia.Bus.RabbitMq" />
        <PackageReference Include="Euonia.Caching" />
        <PackageReference Include="Euonia.Caching.Memory" />
        <PackageReference Include="Euonia.Caching.Redis" />
        <PackageReference Include="Euonia.Caching.Runtime" />
		<PackageReference Include="Euonia.Mapping.Automapper" />
		<PackageReference Include="FluentHttpClient" />
		<PackageReference Include="MailKit" />
		<PackageReference Include="Microsoft.FeatureManagement.AspNetCore" />
	</ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Starfish.Domain\Starfish.Domain.csproj" />
        <ProjectReference Include="..\Starfish.Repository\Starfish.Repository.csproj" />
        <ProjectReference Include="..\Starfish.Transit\Starfish.Transit.csproj" />
    </ItemGroup>
	
    <ItemGroup>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Nerosoft.Starfish.Toolkit" />
        <Using Include="$(RootNamespace).Properties" />
        <Using Include="Microsoft.Extensions.DependencyInjection" />
        <Using Include="System.Diagnostics.CodeAnalysis" />
    </ItemGroup>
</Project>
